// @ts-check

// Auto-generated by update_payloads.py on 2026-03-29 09:53:15 UTC
// Do not edit manually - changes will be overwritten by GitHub Actions

const CUSTOM_ACTION_APPCACHE_REMOVE = "appcache-remove";

/**
 * @typedef {Object} PayloadAuthor
 * @property {string} name
 * @property {string} [github]
 * @property {string} [role]
 */

/**
 * @typedef {Object} PayloadLicense
 * @property {string} type
 * @property {string} [url]
 */

/**
 * @typedef {Object} PayloadVersion
 * @property {string} version
 * @property {string} fileName
 * @property {string} filePath
 * @property {string} downloadUrl
 * @property {string} hash
 * @property {number} fileSize
 * @property {string} releaseDate
 * @property {boolean} isDefault
 * @property {boolean} isPreRelease
 * @property {string[]} changelog
 */

/**
 * @typedef {Object} PayloadInfo
 * @property {string} id
 * @property {string} displayTitle
 * @property {string} description
 * @property {string} author
 * @property {PayloadAuthor[]} authors
 * @property {string} projectUrl
 * @property {PayloadLicense} license
 * @property {string} sourceType
 * @property {string} sourceRepo
 * @property {PayloadVersion[]} versions
 * @property {string[]} [supportedFirmwares]
 * @property {number} [toPort]
 * @property {string} [customAction]
 * @property {boolean} visible
 */

/** @type {PayloadInfo[]} */
const payload_map = [
    {
        id: "etahen",
        displayTitle: "etaHEN",
        description: "AIO HEN",
        author: "LightningMods, Buzzer, sleirsgoevy, ChendoChap, astrelsky, illusion, CTN, SiSTR0, Nomadic",
        authors: [{"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "Buzzer", "github": "https://github.com/Buzzer", "role": "Developer"}, {"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "ChendoChap", "github": "https://github.com/ChendoChap", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}, {"name": "illusion", "github": "https://github.com/illusion", "role": "Developer"}, {"name": "CTN", "github": "https://github.com/CTN", "role": "Developer"}, {"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "Nomadic", "github": "https://github.com/Nomadic", "role": "Developer"}],
        projectUrl: "https://github.com/etaHEN/etaHEN",
        license: {type: "Unknown", url: "https://github.com/etaHEN/etaHEN/blob/main/LICENSE"},
        sourceType: "direct",
        sourceRepo: "etaHEN/etaHEN",
        versions: [
            {
                version: "2.4b",
                fileName: "etaHEN-2.4B.bin",
                filePath: "payloads/etahen/2.4b/etaHEN-2.4B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.4B.bin",
                hash: "93d524497f1653841a9414e059fd0bdc80fbcc97ccd3724c3b3b73d8e34b9b9f",
                fileSize: 4605992,
                releaseDate: "2024-01-15",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "2.3b",
                fileName: "etaHEN-2.3B.bin",
                filePath: "payloads/etahen/2.3b/etaHEN-2.3B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.3B.bin",
                hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                fileSize: 0,
                releaseDate: "2024-01-01",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "2.2b",
                fileName: "etaHEN-2.2B.bin",
                filePath: "payloads/etahen/2.2b/etaHEN-2.2B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.2B.bin",
                hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                fileSize: 0,
                releaseDate: "2023-12-15",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "kstuff",
        displayTitle: "ps5-kstuff",
        description: "FPKG enabler",
        author: "sleirsgoevy, john-tornblom, EchoStretch, buzzer-re, idlesauce, BestPig, LightningMods, zecoxao",
        authors: [{"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}, {"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "buzzer-re", "github": "https://github.com/buzzer-re", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}, {"name": "BestPig", "github": "https://github.com/BestPig", "role": "Developer"}, {"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "zecoxao", "github": "https://github.com/zecoxao", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/ps4jb-payloads/",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "EchoStretch/ps4jb-payloads",
        versions: [
            {
                version: "1.5",
                fileName: "kstuff.elf",
                filePath: "payloads/kstuff/1.5/kstuff.elf",
                downloadUrl: "https://github.com/EchoStretch/ps4jb-payloads/releases/download/kstuff-ps5/kstuff-ps5.elf",
                hash: "02da00b055e39d7bd08e9b59e07420f6368a2c165d6d345c2b734a3186ec4389",
                fileSize: 1491752,
                releaseDate: "2023-10-01",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "byepervisor",
        displayTitle: "Byepervisor HEN",
        description: "FPKG enabler",
        author: "SpecterDev, ChendoChap, flatz, fail0verflow, Znullptr, kiwidog, sleirsgoevy, EchoStretch, LightningMods, BestPig, zecoxao, TheOfficialFloW",
        authors: [{"name": "SpecterDev", "github": "https://github.com/SpecterDev", "role": "Developer"}, {"name": "ChendoChap", "github": "https://github.com/ChendoChap", "role": "Developer"}, {"name": "flatz", "github": "https://github.com/flatz", "role": "Developer"}, {"name": "fail0verflow", "github": "https://github.com/fail0verflow", "role": "Developer"}, {"name": "Znullptr", "github": "https://github.com/Znullptr", "role": "Developer"}, {"name": "kiwidog", "github": "https://github.com/kiwidog", "role": "Developer"}, {"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "BestPig", "github": "https://github.com/BestPig", "role": "Developer"}, {"name": "zecoxao", "github": "https://github.com/zecoxao", "role": "Developer"}, {"name": "TheOfficialFloW", "github": "https://github.com/TheOfficialFloW", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/Byepervisor",
        license: {type: "Unknown", url: "https://github.com/EchoStretch/Byepervisor/blob/main/LICENSE"},
        sourceType: "direct",
        sourceRepo: "EchoStretch/Byepervisor",
        versions: [
            {
                version: "d89a105",
                fileName: "byepervisor.elf",
                filePath: "payloads/byepervisor/d89a105/byepervisor.elf",
                downloadUrl: "https://github.com/EchoStretch/Byepervisor/releases/download/latest/byepervisor.elf",
                hash: "f913ba96bf87561bcc22f1391d2ad58515b3ed0a9e5199d63dbbd9125ec3c317",
                fileSize: 348256,
                releaseDate: "2024-01-20",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["1.00", "1.01", "1.02", "1.12", "1.14", "2.00", "2.20", "2.25", "2.26", "2.30", "2.50", "2.70"],
        toPort: 9021,
        visible: true
    },
    {
        id: "libhijacker",
        displayTitle: "libhijacker game-patch",
        description: "Patches supported games to run at higher framerates, and adds debug menus to certain titles.",
        author: "illusion0001, astrelsky",
        authors: [{"name": "illusion0001", "github": "https://github.com/illusion0001", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}],
        projectUrl: "https://github.com/illusion0001/libhijacker",
        license: {type: "Unknown", url: "https://github.com/illusion0001/libhijacker-game-patch/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "illusion0001/libhijacker-game-patch",
        versions: [
            {
                version: "1.160",
                fileName: "libhijacker-game-patch.v1.160.elf",
                filePath: "payloads/libhijacker/1.160/libhijacker-game-patch.v1.160.elf",
                downloadUrl: "",
                hash: "",
                fileSize: 1162832,
                releaseDate: "",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["3.", "4."],
        visible: true
    },
    {
        id: "websrv",
        displayTitle: "websrv",
        description: "Custom homebrew loader. Runs on port 8080.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/websrv",
        license: {type: "Unknown", url: "https://github.com/ps5-payload-dev/websrv/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/websrv",
        versions: [
            {
                version: "0.30",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.30/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.30/websrv-ps5.elf",
                hash: "65f72e6ebcd0c6311247362aba32c38acb2adbe09039e71c4f573e6db630b430",
                fileSize: 1446784,
                releaseDate: "2026-02-23",
                isDefault: true,
                isPreRelease: false,
                changelog: ["filepicker: allow the selection of either a file or a folder in the same dialog", "elfldr: support launching of remote http(s) payloads", "transmission: fix launch script"]
            },
            {
                version: "0.29",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.29/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.29/websrv-ps5.elf",
                hash: "f018d23536848aa2b20ea9f1c5a685e4829fe0f9b5ea4f83baedf22f0fba58fe",
                fileSize: 1443904,
                releaseDate: "2026-01-01",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "0.28.3",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.28.3/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.28.3/websrv-ps5.elf",
                hash: "5d2b6f609995b92c48e9a9561ad2042cc67b516893a9f1456a4924538603e048",
                fileSize: 1443600,
                releaseDate: "2025-12-08",
                isDefault: false,
                isPreRelease: false,
                changelog: ["retroarch: ensure opengl is disabled", "websrv: improve html dir listing", "websrv: cosmtics"]
            },
            {
                version: "0.28.1",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.28.1/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.28.1/websrv-ps5.elf",
                hash: "f1a65a9f0da384a928745f76f5378da3d31abcb9ee6d35cee6c7709b6452a6d2",
                fileSize: 1443488,
                releaseDate: "2025-11-29",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "0.28",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.28/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.28/websrv-ps5.elf",
                hash: "312cd5b4e4397c8ecce545d429577f3bcb936a0d19a2140d93c4a336f158a2ee",
                fileSize: 1443456,
                releaseDate: "2025-11-25",
                isDefault: false,
                isPreRelease: true,
                changelog: ["\u26a0 This is a pre-release version. Use with caution.", "homebrew.js: add pickDevice()", "fs: fix html rendering of directories"]
            },
            {
                version: "0.27",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.27/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.27/websrv-ps5.elf",
                hash: "d20fb5f499aa55ed48203ec12fec13848d2402f243fcd80aba2e8c2305c4595f",
                fileSize: 1442808,
                releaseDate: "2025-11-08",
                isDefault: false,
                isPreRelease: false,
                changelog: ["make sure stack is aligned before invoking homebrew", "homberew.js: add pickDirectory()"]
            },
            {
                version: "0.26.1",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.26.1/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.26.1/websrv-ps5.elf",
                hash: "60c86099e7fdc7ebdc1d8db6faef950630f9c72b740c2fad28cc3ea8bee06b0f",
                fileSize: 1440344,
                releaseDate: "2025-08-28",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "0.26",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.26/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.26/websrv-ps5.elf",
                hash: "83770ef00cdcbe0289ca866d0495b3d3451885ef1a0378dfd5e03ba06a187896",
                fileSize: 1440208,
                releaseDate: "2025-08-14",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "ftpsrv",
        displayTitle: "ftpsrv",
        description: "FTP server. Runs on port 2121.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/ftpsrv",
        license: {type: "Unknown", url: "https://github.com/ps5-payload-dev/ftpsrv/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/ftpsrv",
        versions: [
            {
                version: "0.18.2",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.18.2/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.18.2/ftpsrv-ps5.elf",
                hash: "03ae8aa1790ac36c10d8035cd99eaaa9b26b6ab04c8f36c12e2e767a6d589b1e",
                fileSize: 174712,
                releaseDate: "2026-02-18",
                isDefault: true,
                isPreRelease: false,
                changelog: ["add command line option for choosing the port to bind to"]
            },
            {
                version: "0.18.1",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.18.1/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.18.1/ftpsrv-ps5.elf",
                hash: "f6aed4e536c4e1132c4ab12c87a49b0e7199e8be11fb9be023a36f4d29240a14",
                fileSize: 174624,
                releaseDate: "2026-02-04",
                isDefault: false,
                isPreRelease: false,
                changelog: ["MLSD: initial commit"]
            },
            {
                version: "0.18",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.18/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.18/ftpsrv-ps5.elf",
                hash: "319a61e677b0b3462c7aebc4767690006ed59003e8bc68e8b35cda97d651e466",
                fileSize: 158136,
                releaseDate: "2026-02-03",
                isDefault: false,
                isPreRelease: false,
                changelog: ["ps4: remount /preinst and /preinst2 with the MTRW command", "ps5: remount /preinst with the MTRW command", "cmd: XCUP is an alias for CDUP, not CWD", "io: retry transfers upon interupts", "srv: ignore character cases when parsing ftp commands", "srv: include version info in greeting message"]
            },
            {
                version: "0.17.2",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.17.2/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.17.2/ftpsrv-ps5.elf",
                hash: "9d08fee421a7439e591fbcae36ce53e3f684e82f4633edd777488cc59b3e5d53",
                fileSize: 157952,
                releaseDate: "2026-01-12",
                isDefault: false,
                isPreRelease: false,
                changelog: ["LIST: set change time to UTC", "PASV: only accept a single data connection", "PORT: plug file descriptor leakage"]
            },
            {
                version: "0.17.1",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.17.1/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.17.1/ftpsrv-ps5.elf",
                hash: "85db8527ca1232a12c68dc2072b0f7aff4b4371aa8fe71e36dd375795fbbc06e",
                fileSize: 157752,
                releaseDate: "2026-01-10",
                isDefault: false,
                isPreRelease: false,
                changelog: ["RETR: use read/write instead of sendfile, it seems to perform better", "LIST: plug fd leak"]
            },
            {
                version: "0.17",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.17/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.17/ftpsrv-ps5.elf",
                hash: "754bcef90345a400859da4b6a39daa9142f8f693996523b7d5d75aedeead355b",
                fileSize: 157720,
                releaseDate: "2026-01-10",
                isDefault: false,
                isPreRelease: false,
                changelog: ["RETR: use sendfile() to transmit files for improved performance and reduced memory footprint", "srv: disable the nagle algorithm (TCP_NODELAY) on active connections"]
            },
            {
                version: "0.16",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.16/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.16/ftpsrv-ps5.elf",
                hash: "81d50402bae30624dcf17a5162caf5af7fabce92690a4b648de6a1d30a3c22aa",
                fileSize: 157624,
                releaseDate: "2026-01-09",
                isDefault: false,
                isPreRelease: false,
                changelog: ["increase SO_SNDBUF and  SO_RCVBUF for improved throughput", "allow ASCII mode to be enabled, but report error when enabled during STOR", "STOR: preallocate readbuf when a new connection is made", "srv: maximize backlog size of incomming connections", "srv: detach from threads so resources of terminated threads are returned to the system", "io: reduce memory footprint", "add test cases for benchmarking transfer speeds"]
            },
            {
                version: "0.15",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.15/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.15/ftpsrv-ps5.elf",
                hash: "fff54cd77827ad9c834339db3c587009e29694830f9268d459d20f65f04717dd",
                fileSize: 157584,
                releaseDate: "2026-01-06",
                isDefault: false,
                isPreRelease: false,
                changelog: ["we only support binary transfer mode for now, report proper error to client", "fix dir listing containing block devices"]
            },
            {
                version: "0.14.3",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.14.3/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.14.3/ftpsrv-ps5.elf",
                hash: "5c9d11399934252992cb92c6f91d52a741a61fec674bca2d10d0b6d307f371bb",
                fileSize: 157312,
                releaseDate: "2025-11-28",
                isDefault: false,
                isPreRelease: false,
                changelog: ["self2elf: speed improvements"]
            },
            {
                version: "0.14.2",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.14.2/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.14.2/ftpsrv-ps5.elf",
                hash: "4178aabd252a93586706e7ab0a6b7821c8e2ead78d6d5bfc713d81bd6b01f7a4",
                fileSize: 157312,
                releaseDate: "2025-11-20",
                isDefault: false,
                isPreRelease: false,
                changelog: ["STOR: increase read buffer size for improved throughput"]
            },
            {
                version: "0.14.1",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.14.1/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.14.1/ftpsrv-ps5.elf",
                hash: "5682d0fb2cbf4aa3ac65d751f3dd99a3c3bdc0a9768c5a3c42be62dd3d2617e8",
                fileSize: 157312,
                releaseDate: "2025-11-19",
                isDefault: false,
                isPreRelease: false,
                changelog: ["self2elf: address potential race condition in self decryption", "self2elf: add several cosmetics and improvements to error handling, including sha256 digest verification", "self2elf: ensure wholes in the ELF file are all zeroed out", "LIST: when in self2elf mode, use the ELF size instead of the SELF size"]
            },
            {
                version: "0.14",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.14/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.14/ftpsrv-ps5.elf",
                hash: "209478f9f0883cd12d135bbf7a073e30478648703fb8ad00477f6db9c6684521",
                fileSize: 155424,
                releaseDate: "2025-11-14",
                isDefault: false,
                isPreRelease: false,
                changelog: ["add SELF to ELF decryption for ps4 and ps5", "RETR: fix resume from offset"]
            },
            {
                version: "0.13",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.13/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.13/ftpsrv-ps5.elf",
                hash: "342bd23205cd5e8d60682c91e57670f4b3df3bbc851d766e848682da79962ac0",
                fileSize: 138064,
                releaseDate: "2025-08-08",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "klogsrv",
        displayTitle: "klogsrv",
        description: "Klog server. Runs on port 3232.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/klogsrv",
        license: {type: "Unknown", url: "https://github.com/ps5-payload-dev/klogsrv/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/klogsrv",
        versions: [
            {
                version: "0.7.1",
                fileName: "klogsrv-ps5.elf",
                filePath: "payloads/klogsrv/0.7.1/klogsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/klogsrv/releases/download/v0.7.1/klogsrv-ps5.elf",
                hash: "3145d87ca89b2b7b09c02e71ed3128a6d14ac633c1ca82229f6cf41a6b85678d",
                fileSize: 134808,
                releaseDate: "2025-10-21",
                isDefault: true,
                isPreRelease: false,
                changelog: ["ps4: optimize with -O2", "make some cosmetics changes"]
            },
            {
                version: "0.7",
                fileName: "klogsrv-ps5.elf",
                filePath: "payloads/klogsrv/0.7/klogsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/klogsrv/releases/download/v0.7/klogsrv-ps5.elf",
                hash: "ec25540cd0fe2ef76bcfb7b9b236b9fa5ba20ed2b7c4b0414c40b8533d00ad15",
                fileSize: 134896,
                releaseDate: "2025-08-14",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "shsrv",
        displayTitle: "shsrv",
        description: "Telnet shell server. Runs on port 2323.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/shsrv",
        license: {type: "Unknown", url: "https://github.com/ps5-payload-dev/shsrv/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/shsrv",
        versions: [
            {
                version: "0.18",
                fileName: "shsrv-ps5.elf",
                filePath: "payloads/shsrv/0.18/shsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/shsrv/releases/download/v0.18/shsrv-ps5.elf",
                hash: "5d53f6a4262b98aa29659ed1a5a56094633394141abd1902ac06b915e901b4bd",
                fileSize: 912952,
                releaseDate: "2025-11-08",
                isDefault: true,
                isPreRelease: false,
                changelog: ["make sure stack is aligned", "add browse command", "add procstat command"]
            },
            {
                version: "0.17",
                fileName: "shsrv-ps5.elf",
                filePath: "payloads/shsrv/0.17/shsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/shsrv/releases/download/v0.17/shsrv-ps5.elf",
                hash: "211b56513fe21d90c0a804418d79ada7638c460ac2a6e0dbfe0d1425e0c893e4",
                fileSize: 912952,
                releaseDate: "2025-08-14",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "gdbsrv",
        displayTitle: "gdbsrv",
        description: "GDB server. Runs on port 2159.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/gdbsrv",
        license: {type: "Unknown", url: "https://github.com/ps5-payload-dev/gdbsrv/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/gdbsrv",
        versions: [
            {
                version: "0.7.3",
                fileName: "gdbsrv-ps5.elf",
                filePath: "payloads/gdbsrv/0.7.3/gdbsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/gdbsrv/releases/download/v0.7.3/gdbsrv-ps5.elf",
                hash: "833d23a3336b5db806541c7d76904d8644caac7247dd2323fc7696c0fe40973e",
                fileSize: 156960,
                releaseDate: "2025-12-21",
                isDefault: true,
                isPreRelease: false,
                changelog: ["ensure the interior gets the SIGCONT when detaching"]
            },
            {
                version: "0.7.2",
                fileName: "gdbsrv-ps5.elf",
                filePath: "payloads/gdbsrv/0.7.2/gdbsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/gdbsrv/releases/download/v0.7.2/gdbsrv-ps5.elf",
                hash: "148e2ce13a8e83c6d678fd38c34d1b9d271ba5ba8ea7dc86473fb9ca5f772b1f",
                fileSize: 156728,
                releaseDate: "2025-11-08",
                isDefault: false,
                isPreRelease: true,
                changelog: ["\u26a0 This is a pre-release version. Use with caution."]
            },
            {
                version: "0.7.1",
                fileName: "gdbsrv-ps5.elf",
                filePath: "payloads/gdbsrv/0.7.1/gdbsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/gdbsrv/releases/download/v0.7.1/gdbsrv-ps5.elf",
                hash: "dee10d057c88f128553ffa33a6ca6f74898e6201642aa9ee48fae54471de735b",
                fileSize: 156688,
                releaseDate: "2025-10-21",
                isDefault: false,
                isPreRelease: false,
                changelog: ["cosmetics"]
            },
            {
                version: "0.7",
                fileName: "gdbsrv-ps5.elf",
                filePath: "payloads/gdbsrv/0.7/gdbsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/gdbsrv/releases/download/v0.7/gdbsrv-ps5.elf",
                hash: "b04b473fc1a6aa61d208662174c35de0736c7100972d4f6aac45052c2cb9ff50",
                fileSize: 156776,
                releaseDate: "2025-08-08",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5debug",
        displayTitle: "ps5debug",
        description: "Debugger",
        author: "SiSTR0, ctn123",
        authors: [{"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "ctn123", "github": "https://github.com/ctn123", "role": "Developer"}],
        projectUrl: "https://github.com/GoldHEN/ps5debug",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "GoldHEN/ps5debug",
        versions: [
            {
                version: "1.0b5",
                fileName: "ps5debug_v1.0b5.elf",
                filePath: "payloads/ps5debug/1.0b5/ps5debug_v1.0b5.elf",
                downloadUrl: "",
                hash: "",
                fileSize: 148808,
                releaseDate: "",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5debug-dizz",
        displayTitle: "ps5debug",
        description: "Debugger, open source version by DizzRL",
        author: "Dizz, astrelsky, John Tornblom, SiSTR0, golden, idlesauce",
        authors: [{"name": "Dizz", "github": "https://github.com/Dizz", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}, {"name": "John Tornblom", "github": "https://github.com/John Tornblom", "role": "Developer"}, {"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "golden", "github": "https://github.com/golden", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/idlesauce/ps5debug",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "idlesauce/ps5debug",
        versions: [
            {
                version: "0.0.1-r2",
                fileName: "ps5debug.elf",
                filePath: "payloads/ps5debug-dizz/0.0.1-r2/ps5debug.elf",
                downloadUrl: "https://github.com/idlesauce/ps5debug/releases/download/v0.0.1-r2/ps5debug.elf",
                hash: "550885996e8e44b050b8bbfabd3e4740076065da1d3468d4798ddbbc22370a2f",
                fileSize: 165928,
                releaseDate: "2025-02-04",
                isDefault: true,
                isPreRelease: false,
                changelog: ["Re-build with latest sdk"]
            },
            {
                version: "0.0.1",
                fileName: "ps5debug.elf",
                filePath: "payloads/ps5debug-dizz/0.0.1/ps5debug.elf",
                downloadUrl: "https://github.com/idlesauce/ps5debug/releases/download/v0.0.1/ps5debug.elf",
                hash: "e34fd39c286d7b8e31b47d72005efe68e62401f35eb20ba7c442e9ad638bca22",
                fileSize: 226960,
                releaseDate: "2024-11-21",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "kstuff-toggle",
        displayTitle: "kstuff-toggle",
        description: "Kstuff Toggle Beta",
        author: "EchoStretch, john-tornblom",
        authors: [{"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/kstuff-toggle",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "EchoStretch/kstuff-toggle",
        versions: [
            {
                version: "0.2",
                fileName: "kstuff-toggle.elf",
                filePath: "payloads/kstuff-toggle/0.2/kstuff-toggle.elf",
                downloadUrl: "https://github.com/EchoStretch/kstuff-toggle/releases/download/latest/kstuff-toggle.elf",
                hash: "b85aac983940ff3b895136bdfdc81cd06af7670b3a8a3c386f08e0a406851ff4",
                fileSize: 112736,
                releaseDate: "2024-01-10",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5-versions",
        displayTitle: "ps5-versions",
        description: "Shows kernel build, os and sdk versions",
        author: "SiSTRo",
        authors: [{"name": "SiSTRo", "github": "https://github.com/SiSTRo", "role": "Developer"}],
        projectUrl: "https://github.com/SiSTR0/ps5-versions",
        license: {type: "Unknown", url: "https://github.com/SiSTR0/ps5-versions/blob/main/LICENSE"},
        sourceType: "github-release",
        sourceRepo: "SiSTR0/ps5-versions",
        versions: [
            {
                version: "1.0",
                fileName: "ps5-versions.elf",
                filePath: "payloads/ps5-versions/1.0/ps5-versions.elf",
                downloadUrl: "https://github.com/SiSTR0/ps5-versions/releases/download/v1.0/ps5-versions.elf",
                hash: "4df615bf70ad51d977f4f2898ae23b7c7349d32afe0e37783d8b62aedd7700be",
                fileSize: 9880,
                releaseDate: "2023-02-15",
                isDefault: true,
                isPreRelease: false,
                changelog: ["Show some version infos of your console.", "Works with Webkit and BD exploit.", "Needs gcc 9 installed.", "[SiSTRo](https://github.com/SiSTR0)"]
            },
        ],
        supportedFirmwares: ["1.", "2.", "3.", "4."],
        visible: true
    },
    {
        id: "rp-get-pin",
        displayTitle: "ps5-remoteplay-get-pin",
        description: "Get Remote Play PIN for offline activated users. Send again to cancel.",
        author: "idlesauce",
        authors: [{"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/idlesauce/ps5-remoteplay-get-pin",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "idlesauce/ps5-remoteplay-get-pin",
        versions: [
            {
                version: "0.1.1",
                fileName: "rp-get-pin.elf",
                filePath: "payloads/rp-get-pin/0.1.1/rp-get-pin.elf",
                downloadUrl: "https://github.com/idlesauce/ps5-remoteplay-get-pin/releases/download/v0.1.1/rp-get-pin.elf",
                hash: "1d611c1856dd2f4b4b6cb42ead1128a7f08a26585788f92de79fa4f67d721472",
                fileSize: 117848,
                releaseDate: "2025-03-09",
                isDefault: true,
                isPreRelease: false,
                changelog: ["Build with newer sdk", "Payload now supports 6.xx-7.xx", "Requires host with updated offsets for 5.xx"]
            },
            {
                version: "0.1",
                fileName: "rp-get-pin.elf",
                filePath: "payloads/rp-get-pin/0.1/rp-get-pin.elf",
                downloadUrl: "https://github.com/idlesauce/ps5-remoteplay-get-pin/releases/download/v0.1/rp-get-pin.elf",
                hash: "c76442b81bcef1af3a3a9ca7e463455a8db3d80495cd9f2e0330ea2edf7de05a",
                fileSize: 116392,
                releaseDate: "2024-12-11",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "appcache-remove",
        displayTitle: "Browser appcache remover",
        description: "Deletes for only the current user in webkit-only mode",
        author: "Storm21CH, idlesauce",
        authors: [{"name": "Storm21CH", "github": "https://github.com/Storm21CH", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/Storm21CH/PS5_Browser_appCache_remove",
        license: {type: "Unknown", url: "https://github.com//blob/main/LICENSE"},
        sourceType: "custom",
        sourceRepo: "",
        versions: [
            {
                version: "1.0",
                fileName: "",
                filePath: "",
                downloadUrl: "",
                hash: "",
                fileSize: 0,
                releaseDate: "2023-01-01",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
        ],
        customAction: "appcache-remove",
        visible: true
    },
];
