// @ts-check

// Auto-generated by update_payloads.py on 2026-03-28 23:00:00 UTC
// Do not edit manually - changes will be overwritten by GitHub Actions

const CUSTOM_ACTION_APPCACHE_REMOVE = "appcache-remove";

/**
 * @typedef {Object} PayloadAuthor
 * @property {string} name
 * @property {string} [github]
 * @property {string} [role]
 */

/**
 * @typedef {Object} PayloadLicense
 * @property {string} type
 * @property {string} [url]
 */

/**
 * @typedef {Object} PayloadVersion
 * @property {string} version
 * @property {string} fileName
 * @property {string} filePath
 * @property {string} downloadUrl
 * @property {string} hash
 * @property {number} fileSize
 * @property {string} releaseDate
 * @property {boolean} isDefault
 * @property {boolean} isPreRelease
 * @property {string[]} changelog
 */

/**
 * @typedef {Object} PayloadInfo
 * @property {string} id
 * @property {string} displayTitle
 * @property {string} description
 * @property {string} author
 * @property {PayloadAuthor[]} authors
 * @property {string} projectUrl
 * @property {PayloadLicense} license
 * @property {string} sourceType
 * @property {string} sourceRepo
 * @property {PayloadVersion[]} versions
 * @property {string[]} [supportedFirmwares]
 * @property {number} [toPort]
 * @property {string} [customAction]
 * @property {boolean} visible
 */

/** @type {PayloadInfo[]} */
const payload_map = [
    {
        id: "etahen",
        displayTitle: "etaHEN",
        description: "AIO HEN",
        author: "LightningMods, Buzzer, sleirsgoevy, ChendoChap, astrelsky, illusion, CTN, SiSTR0, Nomadic",
        authors: [{"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "Buzzer", "github": "https://github.com/Buzzer", "role": "Developer"}, {"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "ChendoChap", "github": "https://github.com/ChendoChap", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}, {"name": "illusion", "github": "https://github.com/illusion", "role": "Developer"}, {"name": "CTN", "github": "https://github.com/CTN", "role": "Developer"}, {"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "Nomadic", "github": "https://github.com/Nomadic", "role": "Developer"}],
        projectUrl: "https://github.com/etaHEN/etaHEN",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "etaHEN/etaHEN",
        versions: [
            {
                version: "2.4b",
                fileName: "etaHEN-2.4B.bin",
                filePath: "payloads/etahen/2.4b/etaHEN-2.4B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.4B.bin",
                hash: "",
                fileSize: 4605992,
                releaseDate: "2024-01-15",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "2.3b",
                fileName: "etaHEN-2.3B.bin",
                filePath: "payloads/etahen/2.3b/etaHEN-2.3B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.3B.bin",
                hash: "",
                fileSize: 0,
                releaseDate: "2024-01-01",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            },
            {
                version: "2.2b",
                fileName: "etaHEN-2.2B.bin",
                filePath: "payloads/etahen/2.2b/etaHEN-2.2B.bin",
                downloadUrl: "https://github.com/etaHEN/etaHEN/raw/main/etaHEN-2.2B.bin",
                hash: "",
                fileSize: 0,
                releaseDate: "2023-12-15",
                isDefault: false,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "kstuff",
        displayTitle: "ps5-kstuff",
        description: "FPKG enabler",
        author: "sleirsgoevy, john-tornblom, EchoStretch, buzzer-re, idlesauce, BestPig, LightningMods, zecoxao",
        authors: [{"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}, {"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "buzzer-re", "github": "https://github.com/buzzer-re", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}, {"name": "BestPig", "github": "https://github.com/BestPig", "role": "Developer"}, {"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "zecoxao", "github": "https://github.com/zecoxao", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/ps4jb-payloads/",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "EchoStretch/ps4jb-payloads",
        versions: [
            {
                version: "1.5",
                fileName: "kstuff.elf",
                filePath: "payloads/kstuff/1.5/kstuff.elf",
                downloadUrl: "https://github.com/EchoStretch/ps4jb-payloads/releases/download/kstuff-ps5/kstuff-ps5.elf",
                hash: "",
                fileSize: 1491752,
                releaseDate: "2023-10-01",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "byepervisor",
        displayTitle: "Byepervisor HEN",
        description: "FPKG enabler",
        author: "SpecterDev, ChendoChap, flatz, fail0verflow, Znullptr, kiwidog, sleirsgoevy, EchoStretch, LightningMods, BestPig, zecoxao, TheOfficialFloW",
        authors: [{"name": "SpecterDev", "github": "https://github.com/SpecterDev", "role": "Developer"}, {"name": "ChendoChap", "github": "https://github.com/ChendoChap", "role": "Developer"}, {"name": "flatz", "github": "https://github.com/flatz", "role": "Developer"}, {"name": "fail0verflow", "github": "https://github.com/fail0verflow", "role": "Developer"}, {"name": "Znullptr", "github": "https://github.com/Znullptr", "role": "Developer"}, {"name": "kiwidog", "github": "https://github.com/kiwidog", "role": "Developer"}, {"name": "sleirsgoevy", "github": "https://github.com/sleirsgoevy", "role": "Developer"}, {"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "LightningMods", "github": "https://github.com/LightningMods", "role": "Developer"}, {"name": "BestPig", "github": "https://github.com/BestPig", "role": "Developer"}, {"name": "zecoxao", "github": "https://github.com/zecoxao", "role": "Developer"}, {"name": "TheOfficialFloW", "github": "https://github.com/TheOfficialFloW", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/Byepervisor",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "EchoStretch/Byepervisor",
        versions: [
            {
                version: "d89a105",
                fileName: "byepervisor.elf",
                filePath: "payloads/byepervisor/d89a105/byepervisor.elf",
                downloadUrl: "https://github.com/EchoStretch/Byepervisor/releases/download/latest/byepervisor.elf",
                hash: "",
                fileSize: 348256,
                releaseDate: "2024-01-20",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["1.00", "1.01", "1.02", "1.12", "1.14", "2.00", "2.20", "2.25", "2.26", "2.30", "2.50", "2.70"],
        toPort: 9021,
        visible: true
    },
    {
        id: "libhijacker",
        displayTitle: "libhijacker game-patch",
        description: "Patches supported games to run at higher framerates, and adds debug menus to certain titles.",
        author: "illusion0001, astrelsky",
        authors: [{"name": "illusion0001", "github": "https://github.com/illusion0001", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}],
        projectUrl: "https://github.com/illusion0001/libhijacker",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "illusion0001/libhijacker-game-patch",
        versions: [
            {
                version: "1.160",
                fileName: "libhijacker-game-patch.v1.160.elf",
                filePath: "payloads/libhijacker/1.160/libhijacker-game-patch.v1.160.elf",
                downloadUrl: "https://github.com/illusion0001/libhijacker-game-patch/releases/download/1.160-75ab26a3/libhijacker-game-patch.v1.160.elf",
                hash: "",
                fileSize: 1162832,
                releaseDate: "2024-01-10",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["3.", "4."],
        visible: true
    },
    {
        id: "websrv",
        displayTitle: "websrv",
        description: "Custom homebrew loader. Runs on port 8080.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/websrv",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/websrv",
        versions: [
            {
                version: "0.28.1",
                fileName: "websrv-ps5.elf",
                filePath: "payloads/websrv/0.28.1/websrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/websrv/releases/download/v0.28.1/websrv-ps5.elf",
                hash: "",
                fileSize: 1443488,
                releaseDate: "2024-01-05",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "ftpsrv",
        displayTitle: "ftpsrv",
        description: "FTP server. Runs on port 2121.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/ftpsrv",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/ftpsrv",
        versions: [
            {
                version: "0.14.3",
                fileName: "ftpsrv-ps5.elf",
                filePath: "payloads/ftpsrv/0.14.3/ftpsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/ftpsrv/releases/download/v0.14.3/ftpsrv-ps5.elf",
                hash: "",
                fileSize: 157312,
                releaseDate: "2024-01-02",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "klogsrv",
        displayTitle: "klogsrv",
        description: "Klog server. Runs on port 3232.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/klogsrv",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/klogsrv",
        versions: [
            {
                version: "0.7.1",
                fileName: "klogsrv-ps5.elf",
                filePath: "payloads/klogsrv/0.7.1/klogsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/klogsrv/releases/download/v0.7.1/klogsrv-ps5.elf",
                hash: "",
                fileSize: 134808,
                releaseDate: "2023-12-15",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "shsrv",
        displayTitle: "shsrv",
        description: "Telnet shell server. Runs on port 2323.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/shsrv",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/shsrv",
        versions: [
            {
                version: "0.18",
                fileName: "shsrv-ps5.elf",
                filePath: "payloads/shsrv/0.18/shsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/shsrv/releases/download/v0.18/shsrv-ps5.elf",
                hash: "",
                fileSize: 912952,
                releaseDate: "2023-12-01",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "gdbsrv",
        displayTitle: "gdbsrv",
        description: "GDB server. Runs on port 2159.",
        author: "john-tornblom",
        authors: [{"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/ps5-payload-dev/gdbsrv",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "ps5-payload-dev/gdbsrv",
        versions: [
            {
                version: "0.7.1",
                fileName: "gdbsrv-ps5.elf",
                filePath: "payloads/gdbsrv/0.7.1/gdbsrv-ps5.elf",
                downloadUrl: "https://github.com/ps5-payload-dev/gdbsrv/releases/download/v0.7.1/gdbsrv-ps5.elf",
                hash: "",
                fileSize: 156688,
                releaseDate: "2023-12-10",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5debug",
        displayTitle: "ps5debug",
        description: "Debugger",
        author: "SiSTR0, ctn123",
        authors: [{"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "ctn123", "github": "https://github.com/ctn123", "role": "Developer"}],
        projectUrl: "https://github.com/GoldHEN/ps5debug",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "GoldHEN/ps5debug",
        versions: [
            {
                version: "1.0b5",
                fileName: "ps5debug_v1.0b5.elf",
                filePath: "payloads/ps5debug/1.0b5/ps5debug_v1.0b5.elf",
                downloadUrl: "https://github.com/GoldHEN/ps5debug/releases/download/1.0b5/ps5debug_v1.0b5.elf",
                hash: "",
                fileSize: 148808,
                releaseDate: "2023-11-20",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5debug-dizz",
        displayTitle: "ps5debug",
        description: "Debugger, open source version by DizzRL",
        author: "Dizz, astrelsky, John Tornblom, SiSTR0, golden, idlesauce",
        authors: [{"name": "Dizz", "github": "https://github.com/Dizz", "role": "Developer"}, {"name": "astrelsky", "github": "https://github.com/astrelsky", "role": "Developer"}, {"name": "John Tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}, {"name": "SiSTR0", "github": "https://github.com/SiSTR0", "role": "Developer"}, {"name": "golden", "github": "https://github.com/golden", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/idlesauce/ps5debug",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "idlesauce/ps5debug",
        versions: [
            {
                version: "0.0.1-r2",
                fileName: "ps5debug_dizz.elf",
                filePath: "payloads/ps5debug-dizz/0.0.1-r2/ps5debug_dizz.elf",
                downloadUrl: "https://github.com/idlesauce/ps5debug/releases/download/v0.0.1/ps5debug.elf",
                hash: "",
                fileSize: 165928,
                releaseDate: "2023-10-25",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "kstuff-toggle",
        displayTitle: "kstuff-toggle",
        description: "Kstuff Toggle Beta",
        author: "EchoStretch, john-tornblom",
        authors: [{"name": "EchoStretch", "github": "https://github.com/EchoStretch", "role": "Developer"}, {"name": "john-tornblom", "github": "https://github.com/john-tornblom", "role": "Developer"}],
        projectUrl: "https://github.com/EchoStretch/kstuff-toggle",
        license: {type: "Unknown", url: ""},
        sourceType: "direct",
        sourceRepo: "EchoStretch/kstuff-toggle",
        versions: [
            {
                version: "0.2",
                fileName: "kstuff-toggle.elf",
                filePath: "payloads/kstuff-toggle/0.2/kstuff-toggle.elf",
                downloadUrl: "https://github.com/EchoStretch/kstuff-toggle/releases/download/latest/kstuff-toggle.elf",
                hash: "",
                fileSize: 112736,
                releaseDate: "2024-01-10",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["3.", "4.", "5."],
        toPort: 9021,
        visible: true
    },
    {
        id: "ps5-versions",
        displayTitle: "ps5-versions",
        description: "Shows kernel build, os and sdk versions",
        author: "SiSTRo",
        authors: [{"name": "SiSTRo", "github": "https://github.com/SiSTRo", "role": "Developer"}],
        projectUrl: "https://github.com/SiSTR0/ps5-versions",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "SiSTR0/ps5-versions",
        versions: [
            {
                version: "1.0",
                fileName: "ps5-versions.elf",
                filePath: "payloads/ps5-versions/1.0/ps5-versions.elf",
                downloadUrl: "https://github.com/SiSTR0/ps5-versions/releases/download/v1.0/ps5-versions.elf",
                hash: "",
                fileSize: 9880,
                releaseDate: "2023-09-15",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        supportedFirmwares: ["1.", "2.", "3.", "4."],
        visible: true
    },
    {
        id: "rp-get-pin",
        displayTitle: "ps5-remoteplay-get-pin",
        description: "Get Remote Play PIN for offline activated users. Send again to cancel.",
        author: "idlesauce",
        authors: [{"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/idlesauce/ps5-remoteplay-get-pin",
        license: {type: "Unknown", url: ""},
        sourceType: "github-release",
        sourceRepo: "idlesauce/ps5-remoteplay-get-pin",
        versions: [
            {
                version: "0.1.1",
                fileName: "rp-get-pin.elf",
                filePath: "payloads/rp-get-pin/0.1.1/rp-get-pin.elf",
                downloadUrl: "https://github.com/idlesauce/ps5-remoteplay-get-pin/releases/download/v0.1.1/rp-get-pin.elf",
                hash: "",
                fileSize: 117848,
                releaseDate: "2023-08-20",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        toPort: 9021,
        visible: true
    },
    {
        id: "appcache-remove",
        displayTitle: "Browser appcache remover",
        description: "Deletes for only the current user in webkit-only mode",
        author: "Storm21CH, idlesauce",
        authors: [{"name": "Storm21CH", "github": "https://github.com/Storm21CH", "role": "Developer"}, {"name": "idlesauce", "github": "https://github.com/idlesauce", "role": "Developer"}],
        projectUrl: "https://github.com/Storm21CH/PS5_Browser_appCache_remove",
        license: {type: "Unknown", url: ""},
        sourceType: "custom",
        sourceRepo: "",
        versions: [
            {
                version: "1.0",
                fileName: "",
                filePath: "",
                downloadUrl: "",
                hash: "",
                fileSize: 0,
                releaseDate: "2023-01-01",
                isDefault: true,
                isPreRelease: false,
                changelog: []
            }
        ],
        customAction: "appcache-remove",
        visible: true
    }
];
